[book]
authors = ["Seiya Nuta"]
language = "ja"
multilingual = false
src = "docs_ja"
title = "Reseaドキュメント"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/zuki/resea"

[output.html.fold]
enable = false
level = 0
